/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package touristinformationcenter;

import java.util.ArrayList;

/**
 *
 * @author Sarah
 */
public class SearchCustGUI extends javax.swing.JFrame {

    TouristInformationCenter tourist = new TouristInformationCenter();
    private ArrayList<Customer> results;    
    private String hotel;
    private String rmNo;
    private boolean[] dates;
    private String fir;
    private String sur;
    private String pho;

    /**
     * Creates new form SearchCustGUI
     */
    public SearchCustGUI(String h, String r, boolean[] d) {
        initComponents();
        hotel = h;
        rmNo = r;
        dates = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLast = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        cboCust = new javax.swing.JComboBox();
        lblResult1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCBooking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResults = new javax.swing.JTextArea();
        btnView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblResult.setText("Customer id:");

        cboCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCustActionPerformed(evt);
            }
        });

        lblResult1.setText("Customer surname:");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setText("Customer search:");

        btnCBooking.setText("Create Booking");
        btnCBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCBookingActionPerformed(evt);
            }
        });

        txaResults.setEditable(false);
        txaResults.setColumns(20);
        txaResults.setRows(5);
        jScrollPane1.setViewportView(txaResults);

        btnView.setText("View Bookings");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResult1)
                        .addGap(51, 51, 51)
                        .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(103, 103, 103))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblResult)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboCust, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResult1)
                    .addComponent(btnSearch))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCBooking)
                    .addComponent(cboCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-412)/2, (screenSize.height-363)/2, 412, 363);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //results.clear();
        cboCust.removeAllItems();
        txaResults.setText(" ");
        if (evt.getSource() == btnSearch) {
            results = tourist.searchForCustomer(txtLast.getText());
            
            for (int i = 0; i < results.size(); i++) {
                cboCust.addItem(i);
                fir = results.get(i).getFirst();
                sur = results.get(i).getSurname();
                pho = results.get(i).getPhone();
                txaResults.append("ID: "+ i + ", Name: "+ fir + " " + sur + ", Phone no: " +pho +"\n");
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cboCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCustActionPerformed

    private void btnCBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCBookingActionPerformed
        // TODO add your handling code here:
        if (hotel == null) {
            SearchHotelGUI searchHGUI = new SearchHotelGUI(sur, fir, pho);
            searchHGUI.setVisible(true);
            searchHGUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } else {
            for (int i = 0; i < results.size(); i++) {
                if(i ==(cboCust.getSelectedItem())) {
                    //System.out.println(i);
                    sur = results.get(i).getSurname();
                    fir = results.get(i).getFirst();
                    pho = results.get(i).getPhone();
                    tourist.addBooking(hotel, rmNo, fir, sur, pho, dates);
               }
            }
        }
    }//GEN-LAST:event_btnCBookingActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         for (int i = 0; i < results.size(); i++) {
                if(i ==(cboCust.getSelectedItem())) {
                    //System.out.println(i);
                    sur = results.get(i).getSurname();                   
                    pho = results.get(i).getPhone();                   
               }
            }    
         
        ViewBookingsGUI view = new ViewBookingsGUI(sur, pho);
        view.setVisible(true);
        view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCustGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCBooking;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox cboCust;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResult1;
    private javax.swing.JTextArea txaResults;
    private javax.swing.JTextField txtLast;
    // End of variables declaration//GEN-END:variables
}
